parameters:
#    first_god.example.class: First\GodBundle\Example

services:
#    first_god.example:
#        class: %first_god.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
