imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    validation: { enable_annotations: true }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true
    
services:
    my.listener:
        class: First\GodBundle\Listener\AddCategoryByUser
        tags:
            - { name: doctrine.event_listener, event: postPersist }

#swiftmailer:
#    delivery_address: me@example.com
