GoogleOauthBundle:
    resource: "@GoogleOauthBundle/Controller/"
    type:     annotation
    prefix:   /

fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
