<?php

namespace First\GodBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

              public function findAllLager19()
              {
                            return $this->getEntityManager()->getRepository( 'FirstGodBundle:Post' )
                                            ->createQueryBuilder( 'p' )
                                            ->where( 'p.author > :author' )
                                            ->setParameter( 'author', 19 )
                                            ->orderBy( 'p.id', 'DESC' )
                                            ->getQuery()
                                            ->getArrayResult();
              }

}